version: 0.0
os: linux
files:
  - source: /
    destination: /var/deployment/vm-backend
hooks:
  BeforeInstall:
    - location: scripts/remove_root_dir
      timeout: 900
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
