version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing completed"
  pre_build:
    commands:
      - echo installing dependencies...
  build:
    commands:
      - npm i
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: .

